"""Initial schema

Revision ID: 606f4aa397a4
Revises: 
Create Date: 2026-08-21 10:08:15.999009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '606f4aa397a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('error_id', sa.UUID(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('recoverability', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('first_occurrence', sa.DateTime(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('is_handled', sa.Boolean(), nullable=False),
    sa.Column('handler', sa.String(length=100), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('is_retryable', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_error_log_job', 'error_log', ['job_id'], unique=False)
    op.create_index('idx_error_log_project', 'error_log', ['project_id'], unique=False)
    op.create_index('idx_error_log_timestamp', 'error_log', ['timestamp'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INTAKE', 'PROCESSING', 'REVIEW', 'COMPLETED', 'FAILED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_created', 'projects', ['created_at'], unique=False)
    op.create_index('idx_project_status', 'projects', ['status'], unique=False)
    op.create_index('idx_project_tmdb', 'projects', ['tmdb_id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('OFFLINE', 'IDLE', 'BUSY', 'STARTING', 'STOPPING', 'ERROR', name='workerstatus'), nullable=False),
    sa.Column('type', sa.Enum('CPU', 'GPU', 'IO', 'HYBRID', name='workertype'), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('memory_gb', sa.Integer(), nullable=True),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('gpu_memory_gb', sa.Integer(), nullable=False),
    sa.Column('current_job_id', sa.UUID(), nullable=True),
    sa.Column('jobs_completed', sa.Integer(), nullable=False),
    sa.Column('jobs_failed', sa.Integer(), nullable=False),
    sa.Column('total_runtime_seconds', sa.BigInteger(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_worker_heartbeat', 'workers', ['last_heartbeat'], unique=False)
    op.create_index('idx_worker_status', 'workers', ['status'], unique=False)
    op.create_index('idx_worker_type', 'workers', ['type'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('SINGLE_EPISODE', 'BATCH_SEASON', 'BATCH_SERIES', 'CUSTOM', name='workflowtype'), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_active', 'workflows', ['is_active'], unique=False)
    op.create_index('idx_workflow_type', 'workflows', ['type'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('VIDEO', 'AUDIO', 'SUBTITLE', 'METADATA', 'CHARACTER_DB', 'VOICE_DB', 'DIALOGUE_TIMELINE', 'SCENE_TIMELINE', 'ANALYSIS_RESULT', 'SYNTHESIS_CONFIG', 'FINAL_VIDEO', 'QA_REPORT', 'ARCHIVE', 'LOG', 'OTHER', name='artifacttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADING', 'PROCESSING', 'READY', 'FAILED', 'ARCHIVED', name='artifactstatus'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('module_id', sa.String(length=20), nullable=True),
    sa.Column('storage_type', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('storage_bucket', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_artifact_id', sa.UUID(), nullable=True),
    sa.Column('ref_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_artifact_job', 'artifacts', ['job_id'], unique=False)
    op.create_index('idx_artifact_project', 'artifacts', ['project_id'], unique=False)
    op.create_index('idx_artifact_status', 'artifacts', ['status'], unique=False)
    op.create_index('idx_artifact_type', 'artifacts', ['type'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'NON_BINARY', 'UNKNOWN', name='gender'), nullable=True),
    sa.Column('age_range', sa.Enum('CHILD', 'TEEN', 'YOUNG_ADULT', 'ADULT', 'SENIOR', 'UNKNOWN', name='agerange'), nullable=True),
    sa.Column('role_type', sa.Enum('MAIN', 'SUPPORTING', 'MINOR', 'CAMEO', 'BACKGROUND', 'UNKNOWN', name='roletype'), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('speech_pattern', sa.Text(), nullable=True),
    sa.Column('relationships', sa.JSON(), nullable=True),
    sa.Column('first_appearance_season', sa.Integer(), nullable=True),
    sa.Column('first_appearance_episode', sa.Integer(), nullable=True),
    sa.Column('first_appearance_timestamp', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('voice_profile_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_character_actor', 'characters', ['actor_id'], unique=False)
    op.create_index('idx_character_project', 'characters', ['project_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'RUNNING', 'WAITING', 'COMPLETED', 'FAILED', 'CANCELLED', 'RETRYING', name='jobstatus'), nullable=False),
    sa.Column('module_id', sa.String(length=20), nullable=True),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('input_artifacts', sa.JSON(), nullable=True),
    sa.Column('output_artifacts', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_stack', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_module', 'jobs', ['module_id'], unique=False)
    op.create_index('idx_job_project', 'jobs', ['project_id'], unique=False)
    op.create_index('idx_job_status', 'jobs', ['status'], unique=False)
    op.create_index('idx_job_worker', 'jobs', ['worker_id'], unique=False)
    op.create_table('voice_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('tts_model', sa.String(length=100), nullable=True),
    sa.Column('tts_model_version', sa.String(length=50), nullable=True),
    sa.Column('tts_config', sa.JSON(), nullable=True),
    sa.Column('pitch_range', sa.String(length=20), nullable=True),
    sa.Column('speed_range', sa.String(length=20), nullable=True),
    sa.Column('emotional_range', sa.JSON(), nullable=True),
    sa.Column('reference_audio_artifact_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_voice_profile_character', 'voice_profiles', ['character_id'], unique=False)
    op.create_index('idx_voice_profile_project', 'voice_profiles', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_voice_profile_project', table_name='voice_profiles')
    op.drop_index('idx_voice_profile_character', table_name='voice_profiles')
    op.drop_table('voice_profiles')
    op.drop_index('idx_job_worker', table_name='jobs')
    op.drop_index('idx_job_status', table_name='jobs')
    op.drop_index('idx_job_project', table_name='jobs')
    op.drop_index('idx_job_module', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_character_project', table_name='characters')
    op.drop_index('idx_character_actor', table_name='characters')
    op.drop_table('characters')
    op.drop_index('idx_artifact_type', table_name='artifacts')
    op.drop_index('idx_artifact_status', table_name='artifacts')
    op.drop_index('idx_artifact_project', table_name='artifacts')
    op.drop_index('idx_artifact_job', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('idx_workflow_type', table_name='workflows')
    op.drop_index('idx_workflow_active', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('idx_worker_type', table_name='workers')
    op.drop_index('idx_worker_status', table_name='workers')
    op.drop_index('idx_worker_heartbeat', table_name='workers')
    op.drop_table('workers')
    op.drop_index('idx_project_tmdb', table_name='projects')
    op.drop_index('idx_project_status', table_name='projects')
    op.drop_index('idx_project_created', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_error_log_timestamp', table_name='error_log')
    op.drop_index('idx_error_log_project', table_name='error_log')
    op.drop_index('idx_error_log_job', table_name='error_log')
    op.drop_table('error_log')
    # ### end Alembic commands ###
