#!/bin/bash
# install.sh — Unattended Development System Installation Script v1.1
# Auto-generated by unattended-dev-system skill
# Enhanced with environment validation, error handling, and security checks

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }

# ============================================
# ENVIRONMENT VALIDATION
# ============================================

validate_environment() {
    log_info "Validating environment..."
    local errors=0

    # Check required commands
    local required_commands=("bash" "git" "curl" "python3")
    for cmd in "${required_commands[@]}"; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            log_error "Required command not found: $cmd"
            ((errors++))
        fi
    done

    # Optional but recommended commands
    local recommended_commands=("tmux" "crontab" "jq" "sed")
    for cmd in "${recommended_commands[@]}"; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            log_warn "Recommended command not found: $cmd (optional)"
        fi
    done

    # Check Python version (if needed)
    if command -v python3 >/dev/null 2>&1; then
        py_version=$(python3 --version 2>&1 | awk '{print $2}' | cut -d'.' -f1,2)
        log_info "Python version: $py_version"
        
        if [ "$(echo "$py_version | cut -d'.' -f1,2)" -lt 3 ]; then
            log_warn "Python 3.11+ recommended, found: $py_version"
        fi
    fi

    # Check git configuration
    if command -v git >/dev/null 2>&1; then
        if ! git config user.name >/dev/null || ! git config user.email >/dev/null; then
            log_warn "Git user.name or user.email not configured"
            log_info "Run: git config --global user.name 'Your Name'"
            log_info "Run: git config --global user.email 'your.email@example.com'"
        fi
    fi

    # Check SSH key for GitHub
    if ssh -T git@github.com 2>&1 | grep -q "successfully authenticated"; then
        log_success "GitHub SSH access configured"
    else
        log_warn "GitHub SSH access not configured (will affect auto-push)"
    fi

    # Check pi CLI
    if ! command -v pi >/dev/null 2>&1; then
        log_error "pi CLI not found. Install from: https://github.com/earendil-works/pi-coding-agent"
        ((errors++))
    fi

    if [ $errors -gt 0 ]; then
        log_error "Environment validation failed with $errors error(s)"
        log_error "Please fix the above issues and re-run install.sh"
        exit 1
    fi

    log_success "Environment validation passed"
}

# ============================================
# PROJECT DETECTION
# ============================================

detect_project() {
    log_info "Detecting project type..."
    
    # Check language
    if [ -f "package.json" ]; then
        PROJECT_LANG="javascript"
        if grep -q '"type": "module"' package.json 2>/dev/null; then
            PROJECT_LANG="typescript"
        fi
        PROJECT_FRAMEWORK=$(grep -oP '(?<="name": ")[^"]+' package.json 2>/dev/null || echo "Node.js")
    elif [ -f "requirements.txt" ] || [ -f "pyproject.toml" ]; then
        PROJECT_LANG="python"
        PROJECT_FRAMEWORK="Python"
        if [ -f "manage.py" ] || [ -f "wsgi.py" ]; then
            PROJECT_FRAMEWORK="Django"
        elif [ -f "app.py" ] || grep -q "fastapi\|uvicorn" requirements.txt 2>/dev/null; then
            PROJECT_FRAMEWORK="FastAPI"
        elif [ -f "pyproject.toml" ] && grep -q "\[tool.poetry\]" pyproject.toml 2>/dev/null; then
            PROJECT_FRAMEWORK="Poetry"
        fi
    elif [ -f "go.mod" ]; then
        PROJECT_LANG="go"
        PROJECT_FRAMEWORK="Go"
    elif [ -f "Cargo.toml" ]; then
        PROJECT_LANG="rust"
        PROJECT_FRAMEWORK="Rust"
    elif [ -f "pom.xml" ] || [ -f "build.gradle" ]; then
        PROJECT_LANG="java"
        PROJECT_FRAMEWORK="Maven/Gradle"
    else
        PROJECT_LANG="generic"
        PROJECT_FRAMEWORK="Generic"
    fi
    
    log_info "Detected: $PROJECT_LANG / $PROJECT_FRAMEWORK"
    
    # Detect test command
    case $PROJECT_LANG in
        python)
            if [ -f "pytest.ini" ] || grep -q "pytest" requirements.txt 2>/dev/null; then
                TEST_COMMAND="pytest tests/ -q"
            elif [ -f "manage.py" ]; then
                TEST_COMMAND="python manage.py test"
            else
                TEST_COMMAND="python -m pytest"
            fi
            ;;
        javascript|typescript)
            TEST_COMMAND="npm test"
            ;;
        go)
            TEST_COMMAND="go test ./..."
            ;;
        rust)
            TEST_COMMAND="cargo test"
            ;;
        java)
            TEST_COMMAND="mvn test"
            ;;
        *)
            TEST_COMMAND="echo 'No test command configured'
            ;;
    esac
    
    log_info "Test command: $TEST_COMMAND"
    
    # Detect git repo
    if [ -d ".git" ]; then
        GIT_REMOTE=$(git remote -v 2>/dev/null | head -1 | awk '{print $2}' | sed 's/\.git$//')
        log_info "Git remote: $GIT_REMOTE"
    else
        GIT_REMOTE="none"
        log_warn "Not a git repository"
    fi
}

# ============================================
# TEMPLATE GENERATION
# ============================================

generate_templates() {
    log_info "Generating templates..."
    
    local project_root
    project_root=$(pwd)
    local project_name
    project_name=$(basename "$project_root")
    
    # Create directories
    mkdir -p "$LOG_DIR" "$TASKS_DIR" "$CHECKPOINT_DIR"
    
    # Generate config.json
    sed \
        -e "s|{{PROJECT_NAME}}|$project_name|g" \
        -e "s|{{PROJECT_ROOT}}|$project_root|g" \
        -e "s|{{LANGUAGE}}|$PROJECT_LANG|g" \
        -e "s|{{FRAMEWORK}}|$PROJECT_FRAMEWORK|g" \
        -e "s|{{TEST_COMMAND}}|$TEST_COMMAND|g" \
        -e "s|{{DRIVER_TIMEOUT}}|7200|g" \
        -e "s|{{ZERO_OUTPUT_FUSE}}|900|g" \
        -e "s|{{GIT_AUTO_PUSH}}|true|g" \
        -e "s|{{COMMIT_PREFIX}}|chore(driver):|g" \
        -e "s|{{PROVIDERS}}|\"provider1/model1\" \"provider2/model2\"|g" \
        -e "s|{{TOTAL_TASKS}}|0|g" \
        -e "s|{{AI_COMMAND}}|pi --provider provider1/model1 -c -p 'Continue working'|g" \
        -e "s|{{AI_PATTERN}}|pi.*provider.*model|g" \
        -e "s|{{SESSION_NAME}}|dev-driver|g" \
        -e "s|{{STUCK_THRESHOLD_MINUTES}}|45|g" \
        templates/config.json.template > .unattended/config.json
    
    # Generate driver.sh
    sed \
        -e "s|{{PROJECT_NAME}}|$project_name|g" \
        -e "s|{{PROJECT_ROOT}}|$project_root|g" \
        -e "s|{{LANGUAGE}}|$PROJECT_LANG|g" \
        -e "s|{{FRAMEWORK}}|$PROJECT_FRAMEWORK|g" \
        -e "s|{{TEST_COMMAND}}|$TEST_COMMAND|g" \
        -e "s|{{DRIVER_TIMEOUT}}|7200|g" \
        -e "s|{{ZERO_OUTPUT_FUSE}}|900|g" \
        -e "s|{{GIT_AUTO_PUSH}}|true|g" \
        -e "s|{{COMMIT_PREFIX}}|chore(driver):|g" \
        -e "s|{{PROVIDERS}}|\"provider1/model1\" \"provider2/model2\"|g" \
        -e "s|{{TOTAL_TASKS}}|0|g" \
        -e "s|{{AI_COMMAND}}|pi --provider provider1/model1 -c -p 'Continue working'|g" \
        -e "s|{{AI_PATTERN}}|pi.*provider.*model|g" \
        -e "s|{{SESSION_NAME}}|dev-driver|g" \
        -e "s|{{STUCK_THRESHOLD_MINUTES}}|45|g" \
        templates/driver.sh.template > driver.sh
    
    # Generate watchdog.sh
    sed \
        -e "s|{{PROJECT_ROOT}}|$project_root|g" \
        -e "s|{{SESSION_NAME}}|dev-driver|g" \
        -e "s|{{STUCK_THRESHOLD_MINUTES}}|45|g" \
        -e "s|{{AI_PATTERN}}|pi.*provider.*model|g" \
        templates/watchdog.sh.template > watchdog.sh
    
    # Generate orchestrator.py
    cp templates/orchestrator.py.template orchestrator.py
    
    # Generate README
    sed \
        -e "s|{{PROJECT_NAME}}|$project_name|g" \
        -e "s|{{LANGUAGE}}|$PROJECT_LANG|g" \
        -e "s|{{FRAMEWORK}}|$PROJECT_FRAMEWORK|g" \
        -e "s|{{PROJECT_ROOT}}|$project_root|g" \
        -e "s|{{GENERATED_DATE}}|$(date '+%Y-%m-%d')|g" \
        templates/docs/README.template.md > README.md
    
    # Generate QUICKSTART.md
    sed \
        -e "s|{{PROJECT_NAME}}|$project_name|g" \
        -e "s|{{LANGUAGE}}|$PROJECT_LANG|g" \
        -e "s|{{FRAMEWORK}}|$PROJECT_FRAMEWORK|g" \
        -e "s|{{PROJECT_ROOT}}|$project_root|g" \
        -e "s|{{GENERATED_DATE}}|$(date '+%Y-%m-%d')|g" \
        templates/docs/QUICKSTART.md
    
    # Create directories
    mkdir -p .unattended/{tasks/{todo,doing,done},checkpoints,logs}
    
    # Make scripts executable
    chmod +x driver.sh
    chmod +x watchdog.sh
    
    log_success "Templates generated successfully"
}

# ============================================
# CONFIGURATION
# ============================================

configure_providers() {
    log_info "Configuring AI providers..."
    
    echo ""
    echo "Available providers (examples):"
    echo "  - zai-coding-cn/glm-4.7"
    echo "  - deepseek/deepseek-v4-flash"
    echo "  - anthropic/claude-sonnet-4-5"
    echo "  - openai/gpt-5.1"
    echo ""
    
    read -p "Enter primary provider (e.g., zai-coding-cn/glm-4.7): " provider1
    read -p "Enter fallback provider (e.g., deepseek/deepseek-v4-flash): " provider2
    
    if [ -z "$provider1" ]; then
        provider1="zai-coding-cn/glm-4.7"
        log_warn "Using default primary provider: $provider1"
    fi
    
    if [ -z "$provider2" ]; then
        provider2="deepseek/deepseek-v4-flash"
        log_warn "Using default fallback provider: $provider2"
    fi
    
    # Update config
    sed -i "s|\"provider1/model1\" \"provider2/model2\"|\"$provider1\" \"$provider2\"|g" .unattended/config.json
    sed -i "s|provider1/model1|$provider1|g" .unattended/config.json
    sed -i "s|provider2/model2|$provider2|g" .unattended/config.json
    
    log_success "Providers configured: $provider1 (primary), $provider2 (fallback)"
}

# ============================================
# TESTING
# ============================================

test_installation() {
    log_info "Testing installation..."
    
    # Test scripts exist
    if [ ! -f "driver.sh" ]; then
        log_error "driver.sh not found"
        exit 1
    fi
    
    if [ ! -f "watchdog.sh" ]; then
        log_error "watchdog.sh not found"
        exit 1
    fi
    
    if [ ! -f "orchestrator.py" ]; then
        log_error "orchestrator.py not found"
        exit 1
    fi
    
    # Test scripts are valid bash
    if ! bash -n driver.sh 2>/dev/null; then
        log_error "driver.sh has syntax errors"
        exit 1
    fi
    
    if ! bash -n watchdog.sh 2>/dev/null; then
        log_error "watchdog.sh has syntax errors"
        exit 1
    fi
    
    # Test Python script
    if ! python3 -m py_compile orchestrator.py 2>/dev/null; then
        log_error "orchestrator.py has syntax errors"
        exit 1
    fi
    
    # Test config.json is valid JSON
    if ! python3 -c "import json; json.load(open('.unattended/config.json')" 2>/dev/null; then
        log_error ".unattended/config.json has invalid JSON"
        exit 1
    fi
    
    log_success "All tests passed"
}

# ============================================
# SETUP COMPLETE
# ============================================

setup_complete() {
    echo ""
    echo "╔══════════════════════════════════════════════════════════════════╗"
    echo "║          Unattended Dev System - Installation Complete! v1.1                           ║"
    "╚═════════════════════════════════════════════════════╗"
    echo ""
    log_info "Installation completed successfully!"
    echo ""
    echo "📁 Created files:"
    echo "  - driver.sh           (Enhanced with error handling, security checks)"
    echo "  - watchdog.sh         (Platform-aware, improved recovery)"
    "  - orchestrator.py     (Auto orchestrator, enhanced)"
    "  - .unattended/        (Working directory)"
    "  - .unattended/config.json  (Configuration with advanced options)"
    echo ""
    echo "🚀 Quick Start:"
    echo ""
    echo "  1. Start driver (in tmux):"
    echo "     tmux new-session -d -s dev-driver './driver.sh'"
    echo ""
    echo "  2. Install watchdog (cron):"
    echo "     ( crontab -l 2>/dev/null | grep -v watchdog.sh ; \\"
    echo "       echo '*/10 * * * * * \$(pwd)/watchdog.sh' ) | crontab -"
    echo ""
    echo " 3. Monitor logs:"
    echo "     tail -f .unattended/logs/driver.log"
    echo ""
    echo "  4. View status:"
    echo "     python orchestrator.py --status"
    echo ""
    echo "  5. Save checkpoint:"
    echo "     python orchestrator.py --save <phase> <msg> <next> <context>"
    echo ""
    echo "⚙️  Configuration:"
    echo "     Edit: .unattended/config.json"
    echo ""
    echo "📚 Documentation:"
    echo "     - Read: cat SKILL.md"
    echo "     - Status: cat .unattended/status.yaml"
    echo ""
    echo "🛑 Stop System:"
    echo "     tmux kill-session -t dev-driver"
    echo "     crontab -l | grep -v watchdog.sh | crontab -"
    echo ""
    log_success "Ready to use!"
}

# ============================================
# MAIN
# ============================================

main() {
    echo "╔══════════════════════════════════════════════════════════════════╗"
    echo "║       Unattended Development System - Installer v1.1                         ║"
    echo "╚═══════════════════════════════════════════════════════╗"
    echo ""
    
    # Step 1: Environment validation
    validate_environment
    
    # Step 2: Project detection
    detect_project
    
    # Step 3: Template generation
    generate_templates
    
    # Step 4: Configure providers
    echo ""
    read -p "Configure AI providers now? (Y/n): " configure_providers_input
    if [[ "$configure_providers_input" =~ ^[Yy]$|^$ ]]; then
        configure_providers
    else
        log_warn "Using default providers (please edit .unattended/config.json)"
    fi
    
    # Step 5: Test installation
    test_installation
    
    # Step 6: Setup complete
    setup_complete
}

cd "$(dirname "$0")"
main "$@"
