#!/bin/bash
# test-skill.sh - Test the unattended-dev-system skill v1.2
# Auto-generated by unattended-dev-system skill

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

log_success() { echo -e "${GREEN}✅ $*${NC}"; }
log_error() { echo -e "${RED}❌ $*${NC}"; }
log_info() { echo -e "${GREEN}ℹ️  $*${NC}"; }
log_warn() { echo -e "${YELLOW}⚠️  $*${NC}"; }

SKILL_DIR="$HOME/.pi/agent/skills/unattended-dev-system"
echo "========================================"
echo "Unattended Dev System Skill - Test Suite v1.2"
echo "========================================"
echo ""

# Count files
echo "📁 Checking skill files..."
file_count=$(find "$SKILL_DIR" -type f \( -name "*.md" -o -name "*.sh" -o -name "*.py" -o -name "*.json" \) 2>/dev/null | wc -l)
echo "  - Found $file_count files in skill directory"
echo ""

# Test 1: Check SKILL.md exists
if [ -f "$SKILL_DIR/SKILL.md" ]; then
    log_success "SKILL.md exists"
else
    log_error "SKILL.md not found!"
    exit 1
fi

# Test 2: Check README.md exists and has correct content
if [ -f "$SKILL_DIR/README.md" ]; then
    log_success "README.md exists"
    if grep -q "Unattended Dev System" "$SKILL_DIR/README.md" 2>/dev/null; then
        log_success "README.md has correct content"
    else
        log_error "README.md missing or incorrect"
        exit 1
    fi
else
    log_error "README.md missing!"
    exit 1
fi

# Test 3: Check install.sh exists and is executable
if [ -f "$SKILL_DIR/install.sh" ]; then
    if [ -x "$SKILL_DIR/install.sh" ]; then
        log_success "install.sh exists and executable"
    else
        log_error "install.sh not found or not executable"
        exit 1
    fi
else
    log_error "install.sh not found!"
    exit 1
fi

# Test 4: Check test-skill.sh exists
if [ -f "$SKILL_DIR/test-skill.sh" ]; then
    if [ -x "$SKILL_DIR/test-skill.sh" ]; then
        log_success "test-skill.sh exists and executable"
    else
        log_error "test-skill.sh not found or not executable"
        exit 1
    fi
else
    log_error "test-skill.sh not found!"
    exit 1
fi

# Test 5: Check templates directory
if [ -d "$SKILL_DIR/templates" ]; then
    template_count=$(find "$SKILL_DIR/templates" -type f 2>/dev/null | wc -l)
    log_success "Templates directory exists (found $template_count files)"
else
    log_error "templates directory not found!"
    exit 1
fi

# Test 6: Check templates have required placeholders
echo ""
echo "🔍 Validating template placeholders..."

# Check driver.sh template
missing_count=0
required_driver_vars=("PROJECT_NAME" "PROJECT_ROOT" "LANGUAGE" "FRAMEWORK" "TEST_COMMAND")
for var in "${required_driver_vars[@]}"; do
    if ! grep -q "$var" "$SKILL_DIR/templates/driver.sh.template" 2>/dev/null; then
        log_error "driver.sh.template missing required placeholder: $var"
        missing_count=$((missing_count + 1))
    fi
done

if [ $missing_count -eq 0 ]; then
    log_success "All required placeholders present"
else
    log_error "$missing_count required placeholders missing"
    exit 1
fi

# Test 7: Validate Python script syntax
if [ -f "$SKILL_DIR/templates/orchestrator.py.template" ]; then
    if python3 -m py_compile "$SKILL_DIR/templates/orchestrator.py.template" 2>/dev/null; then
        log_success "orchestrator.py.template has valid Python syntax"
    else
        log_error "orchestrator.py.template has syntax errors"
        exit 1
    fi
fi

# Test 8: Test bash scripts syntax
if bash -n "$SKILL_DIR/templates/driver.sh.template" 2>/dev/null; then
    log_success "driver.sh.template has valid bash syntax"
else
    log_error "driver.sh.template has syntax errors"
    exit 1
fi

# Test 9: Check watchdog.sh syntax
if bash -n "$SKILL_DIR/templates/watchdog.sh.template" 2>/dev/null; then
    log_success "watchdog.sh.template has valid bash syntax"
else
    log_error "watchdog.sh.template has syntax errors"
    exit 1
fi

# Test 9b: Check shutdown.sh syntax
if bash -n "$SKILL_DIR/templates/shutdown.sh.template" 2>/dev/null; then
    log_success "shutdown.sh.template has valid bash syntax"
else
    log_error "shutdown.sh.template has syntax errors"
    exit 1
fi

# Test 10: Test config.json syntax
if python3 -c "import json; json.load(open('$SKILL_DIR/templates/config.json.template'))" 2>/dev/null; then
    log_success "config.json.template has valid JSON syntax"
else
    log_error "config.json.template has invalid JSON syntax"
    exit 1
fi

# Test 11: v1.1.1 regression checks (guard against the code-review bugs)
echo ""
echo "🔧 v1.1.1 regression checks..."

# R1: validate_path / validate_ai_command are CALLED (not dead code)
DRV="$SKILL_DIR/templates/driver.sh.template"
if grep -q 'validate_path "\$REPO"' "$DRV" && grep -q 'validate_ai_command "{{AI_COMMAND}}"' "$DRV"; then
    log_success "R1: validate_* functions are called (not dead code)"
else
    log_error "R1: validate_* functions defined but never called"
    exit 1
fi

# R2: git uses correct status --porcelain flag
if grep -q 'git -C "\$REPO" status --porcelain' "$DRV"; then
    log_success "R2: auto_commit uses 'git status --porcelain'"
else
    log_error "R2: auto_commit has invalid 'git --porcelain' flag"
    exit 1
fi

# R3: watchdog has no \$REPOPO typo
WDOG="$SKILL_DIR/templates/watchdog.sh.template"
if grep -q '\$REPOPO' "$WDOG"; then
    log_error "R3: watchdog still has \$REPOPO typo"
    exit 1
else
    log_success "R3: watchdog has no \$REPOPO typo"
fi

# R4: watchdog calls detect_platform and get_file_age returns age
if grep -q '^detect_platform$' "$WDOG" && grep -q 'now=\$(date +%s)' "$WDOG"; then
    log_success "R4: watchdog detect_platform called; get_file_age returns age"
else
    log_error "R4: watchdog platform/age logic broken"
    exit 1
fi

# R5: install.sh substitutes PROJECT_NAME into watchdog render
if grep -B6 'watchdog.sh.template > watchdog.sh' "$SKILL_DIR/install.sh" | grep -q 'PROJECT_NAME'; then
    log_success "R5: watchdog render substitutes {{PROJECT_NAME}}"
else
    log_error "R5: {{PROJECT_NAME}} not substituted into watchdog.sh"
    exit 1
fi

# R6: driver supports --dry-run CLI arg and reads config.json
if grep -q -- '--dry-run' "$DRV" && grep -q 'load_cfg' "$DRV"; then
    log_success "R6: driver supports --dry-run and reads config.json"
else
    log_error "R6: driver --dry-run / config loading missing"
    exit 1
fi

# R7: shutdown.sh.template exists with required placeholders (v1.2 auto-stop)
SD="$SKILL_DIR/templates/shutdown.sh.template"
if [ -f "$SD" ] && grep -q '{{PROJECT_ROOT}}' "$SD" && grep -q '{{PROJECT_NAME}}' "$SD" && grep -q '{{SESSION_NAME}}' "$SD" && grep -q 'STOPPED_MARKER' "$SD"; then
    log_success "R7: shutdown.sh.template exists with placeholders + STOPPED marker"
else
    log_error "R7: shutdown.sh.template missing or incomplete"
    exit 1
fi

# R8: driver calls shutdown.sh on completion and exits (no infinite loop after done)
if grep -q 'shutdown.sh' "$DRV" && grep -q 'LOG_DIR/STOPPED' "$DRV"; then
    log_success "R8: driver auto-stops via shutdown.sh + honors STOPPED marker"
else
    log_error "R8: driver lacks completion auto-stop"
    exit 1
fi

# R9: watchdog honors STOPPED marker and triggers shutdown on completion
WD="$SKILL_DIR/templates/watchdog.sh.template"
if grep -q 'LOG_DIR/STOPPED' "$WD" && grep -q 'shutdown.sh' "$WD"; then
    log_success "R9: watchdog honors STOPPED marker + triggers shutdown on completion"
else
    log_error "R9: watchdog lacks STOPPED guard / shutdown trigger"
    exit 1
fi

# R10: install.sh generates and validates shutdown.sh
INSTALL="$SKILL_DIR/install.sh"
if grep -q 'shutdown.sh.template > shutdown.sh' "$INSTALL" && grep -q 'bash -n shutdown.sh' "$INSTALL" && grep -q 'chmod +x shutdown.sh' "$INSTALL"; then
    log_success "R10: install.sh generates, chmods and syntax-checks shutdown.sh"
else
    log_error "R10: install.sh does not fully wire up shutdown.sh"
    exit 1
fi

log_success "All regression checks passed (v1.1.1: 6 + v1.2: 4)"

# Test 12: Summary
echo ""
echo "========================================"
log_success "✅ All tests passed!"
echo "========================================"
echo ""
echo "Test Summary:"
echo "  - Templates: 5 files validated"
echo "  - Bash scripts: 2 files validated"
echo "  - Python script: 1 file validated"
echo "  - JSON config: 1 file validated"
echo "  - Regression checks: 10 passed (v1.1.1 + v1.2 auto-stop)"
echo ""
echo "📊 Test Result: ALL PASSED"
echo ""
echo "📋 Next Steps:"
echo "  1. Review findings in docs/CODE_REVIEW_FINDINGS.md"
echo "  2. Address critical security issues (S-001, S-002, S-003)"
echo "  3. Apply improvements"
echo "  4. Re-run test"
echo ""
log_success "Skill is ready to use!"
echo ""
echo "Run: /unattended-dev-system in your project directory"

echo "========================================"
echo "Test completed successfully at $(date '+%Y-%m-%d %H:%M:%S')"
echo "========================================"
