#!/bin/bash
# test-skill.sh - Test the unattended-dev-system skill v1.1
# Auto-generated by unattended-dev-system skill

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

log_success() { echo -e "${GREEN}✅ $*${NC}"; }
log_error() { echo -e "${RED}❌ $*${NC}"; }
log_info() { echo -e "${GREEN}ℹ️  $*${NC}"; }
log_warn() { echo -e "${YELLOW}⚠️  $*${NC}"; }

SKILL_DIR="$HOME/.pi/agent/skills/unattended-dev-system"
echo "========================================"
echo "Unattended Dev System Skill - Test Suite v1.1"
echo "========================================"
echo ""

# Count files
echo "📁 Checking skill files..."
file_count=$(find "$SKILL_DIR" -type f \( -name "*.md" -o -name "*.sh" -o -name "*.py" -o -name "*.json" \) 2>/dev/null | wc -l)
echo "  - Found $file_count files in skill directory"
echo ""

# Test 1: Check SKILL.md exists
if [ -f "$SKILL_DIR/SKILL.md" ]; then
    log_success "SKILL.md exists"
else
    log_error "SKILL.md not found!"
    exit 1
fi

# Test 2: Check README.md exists and has correct content
if [ -f "$SKILL_DIR/README.md" ]; then
    log_success "README.md exists"
    if grep -q "Unattended Dev System" "$SKILL_DIR/README.md" 2>/dev/null; then
        log_success "README.md has correct content"
    else
        log_error "README.md missing or incorrect"
        exit 1
    fi
else
    log_error "README.md missing!"
    exit 1
fi

# Test 3: Check install.sh exists and is executable
if [ -f "$SKILL_DIR/install.sh" ]; then
    if [ -x "$SKILL_DIR/install.sh" ]; then
        log_success "install.sh exists and executable"
    else
        log_error "install.sh not found or not executable"
        exit 1
    fi
else
    log_error "install.sh not found!"
    exit 1
fi

# Test 4: Check test-skill.sh exists
if [ -f "$SKILL_DIR/test-skill.sh" ]; then
    if [ -x "$SKILL_DIR/test-skill.sh" ]; then
        log_success "test-skill.sh exists and executable"
    else
        log_error "test-skill.sh not found or not executable"
        exit 1
    fi
else
    log_error "test-skill.sh not found!"
    exit 1
fi

# Test 5: Check templates directory
if [ -d "$SKILL_DIR/templates" ]; then
    template_count=$(find "$SKILL_DIR/templates" -type f 2>/dev/null | wc -l)
    log_success "Templates directory exists (found $template_count files)"
else
    log_error "templates directory not found!"
    exit 1
fi

# Test 6: Check templates have required placeholders
echo ""
echo "🔍 Validating template placeholders..."

# Check driver.sh template
missing_count=0
required_driver_vars=("PROJECT_NAME" "PROJECT_ROOT" "LANGUAGE" "FRAMEWORK" "TEST_COMMAND")
for var in "${required_driver_vars[@]}"; do
    if ! grep -q "$var" "$SKILL_DIR/templates/driver.sh.template" 2>/dev/null; then
        log_error "driver.sh.template missing required placeholder: $var"
        ((missing_count++))
    fi
done

if [ $missing_count -eq 0 ]; then
    log_success "All required placeholders present"
else
    log_error "$missing_count required placeholders missing"
    exit 1
fi

# Test 7: Validate Python script syntax
if [ -f "$SKILL_DIR/templates/orchestrator.py.template" ]; then
    if python3 -m py_compile "$SKILL_DIR/templates/orchestrator.py.template" 2>/dev/null; then
        log_success "orchestrator.py.template has valid Python syntax"
    else
        log_error "orchestrator.py.template has syntax errors"
        exit 1
    fi
fi

# Test 8: Test bash scripts syntax
if bash -n "$SKILL_DIR/templates/driver.sh.template" 2>/dev/null; then
    log_success "driver.sh.template has valid bash syntax"
else
    log_error "driver.sh.template has syntax errors"
    exit 1
fi

# Test 9: Check watchdog.sh syntax
if bash -n "$SKILL_DIR/templates/watchdog.sh.template" 2>/dev/null; then
    log_success "watchdog.sh.template has valid bash syntax"
else
    log_error "watchdog.sh.template has syntax errors"
    exit 1
fi

# Test 10: Test config.json syntax
if python3 -c "import json; json.load(open('$SKILL_DIR/templates/config.json.template'))" 2>/dev/null; then
    log_success "config.json.template has valid JSON syntax"
else
    log_error "config.json.template has invalid JSON syntax"
    exit 1
fi

# Test 11: Summary
echo ""
echo "========================================"
log_success "✅ All tests passed!"
echo "========================================"
echo ""
echo "Test Summary:"
echo "  - Templates: 4 files validated"
echo "  - Bash scripts: 2 files validated"
echo "  - Python script: 1 file validated"
echo "  - JSON config: 1 file validated"
echo ""
echo "📊 Test Result: ALL PASSED"
echo ""
echo "📋 Next Steps:"
echo "  1. Review findings in docs/CODE_REVIEW_FINDINGS.md"
echo "  2. Address critical security issues (S-001, S-002, S-003)"
echo "  3. Apply improvements"
echo "  4. Re-run test"
echo ""
log_success "Skill is ready to use!"
echo ""
echo "Run: /unattended-dev-system in your project directory"

echo "========================================"
echo "Test completed successfully at $(date '+%Y-%m-%d %H:%M:%S')"
echo "========================================"
